name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libpq-dev
    
    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip setuptools wheel
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install -e .
    
    - name: Lint with flake8
      run: |
        flake8 job_instruction_downloader --exclude=.venv,build,dist --max-line-length=120
    
    - name: Type check with mypy
      run: |
        mypy job_instruction_downloader --ignore-missing-imports
    
    - name: Test with pytest
      run: |
        pytest job_instruction_downloader/tests/ -v --tb=short
    
    - name: Check Python syntax
      run: |
        python -m py_compile $(find job_instruction_downloader -name "*.py")

  build:
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.12
      uses: actions/setup-python@v4
      with:
        python-version: 3.12
    
    - name: Install build dependencies
      run: |
        python -m pip install --upgrade pip build
    
    - name: Build package
      run: |
        python -m build
    
    - name: Check package
      run: |
        python -m pip install dist/*.whl
        python -c "import job_instruction_downloader; print('Package import successful')"
